### ISSUE TITLE
Default import does not work as expected

### ISSUE THREAD

**Issue by mateuszdyda** [Financial-Times/n-logger#113]
Hi, we want to use n-logger to our Node (v15.4.0) project with ESM modules. For some reason the default import of n-logger doesn’t quite work as expected.

This doesn’t work:
```
import logger from '@financial-times/n-logger';
logger.info('hello')
```
We get an error `logger.info is not a function`

Only something like this works:
```
import logger from '@financial-times/n-logger';
logger.default.info('hello')
```

**Comment by Rudy-Hentzen** [comment]
@mateuszdyda I had the same issue, I ended up creating a 'wrapper' as I could not find another solution e.g.

'logger-wrapper.js'
```
import logger from '@financial-times/n-logger';

export default logger.default;
```

Then in some-file-that-needs-logging.js
```
import logger from '../lib/logger-wrapper';
```


I know this is a **bit** late, perhaps you found a better solution 😅
