### ISSUE TITLE
Weird output if you pass a string as a meta

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/n-logger#42]
The logger gets very confused if you use a **string** as a meta.

```js
logger.info('Here is some info', 'foo');
```

Output:

```
Here is some info 0=f 1=o 2=o level=info
```

The `'foo'` gets enumerated as `0=f 1=o 2=o` (this quickly gets out of hand if the string is much longer!).

**Comment by ironsidevsquincy** [comment]
Yup, you can only have one string message

**Comment by callumlocke** [comment]
Is that by design? Why not allow a string as a payload?

**Comment by ironsidevsquincy** [comment]
By design. Why would you want to supply tow strings? What would the logger do with them? e.g. what would Splunk do with two string?

**Comment by callumlocke** [comment]
I don't know about Splunk, does that expect any payload to be an object?

> Why would you want to supply two strings?

I do that all the time. Most logging tools (like `console.log` or [debug](https://github.com/visionmedia/debug)) are very happy to be given a payload of any type. For example:

```
debug('Got response from remote server with X-Foo header:', headers.xFoo)
```

I don't mind having to make an exception for n-logger, but if so, it would be good if it could throw an error when passed an illegal payload type, rather than blindly enumerating it.

**Comment by ironsidevsquincy** [comment]
Didn't mean Splunk specifically, but any output
Looks like you expect it to concat all the strings into one. Could do that, yeah. Might be weird if you do something like

```logger.log('foo', { bar: 'bar' }, 'baz')```

And the string that's 'logged' is `foobaz`. Might not be though

Docs do say it only takes one message, but happy to take a PR for this

**Comment by callumlocke** [comment]
Not sure about concatenating things in the wrong order. I guess the simplest change would be to throw an error when passed a string as a meta. I'm happy to do a PR for that.

**Comment by ironsidevsquincy** [comment]
No sure about throwing an error, as we don't do type checking anywhere else and reticent to enforce something like that

I'd vote for concat or just throw away the string. Is this a massive issue though? Could just put a note in the docs saying `if output looks like ..., you're probably passing in a string as the meta object`
