### ISSUE TITLE
Migrate to Splunk HEC

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/n-logger#55]
We're currently using a Splunk transport, sending messages to EC2 instances.

Would be good if we skipped the middle-man and send logs to Splunk directly with the HEC endpoint.

**Comment by kitkat119** [comment]
* Allow for both so we can migrate one by one
* Get a token we can put in shared vault secrets/teams/next/shared/production
* `SPLUNK_URL` and then `SPLUNK_HEC_URL`

**Comment by kitkat119** [comment]
Talk with the tooling team about using Splunk HEC.

**Comment by Limess** [comment]
@kitkat119 believe you want [#foundation_services](https://financialtimes.slack.com/archives/C3QLCEZKP) rather than tooling!
