### ISSUE TITLE
Update to Winston 3

### ISSUE THREAD

**Issue by Limess** [Financial-Times/n-logger#67]
Winston 3 has been released: https://godaddy.github.io/2018/06/12/announcing-winston-3/

Winston 2 was getting pretty long in the tooth, it seems it was put on hold for a while until ES features caught up.

While there's no benchmarks, there is a suggestion of increased performance: 
> Modernize and performance optimize a now seven year old codebase to ES6 (which it turns out was necessary to meet the API goals).

See the upgrade guide: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md

**Comment by Limess** [comment]
Someone did a benchmark which suggests a significant speedup (caveat, no methodology or test cases included): https://gist.github.com/indexzero/659f81b722b6419134f6b56fab5d7b59

**Comment by rowanmanning** [comment]
We're probably gonna end up switching to Pino instead https://github.com/Financial-Times/dotcom-reliability-kit/pull/211
